name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Setup SDL2 frameworks
        id: sdl2
        uses: ./
        with:
          sdl2: 2.26.4
          sdl2-ttf: 2.20.2
          sdl2-image: 2.6.3
          sdl2-mixer: 2.6.3
      - name: Upload temp working directory if failed
        uses: actions/upload-artifact@v3
        if: ${{ failure() && steps.sdl2.conclusion == 'failure' }}
        with:
          name: temp
          path: '/Users/runner/work/_temp'
      - name: Inspect local Framework directory
        run: 'find ~/Library/Frameworks'
