name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 20.x
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20.x
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - name: Setup SDL2 frameworks
        uses: ./
        with:
          sdl2: latest
          sdl2-ttf: latest
          sdl2-image: latest
          sdl2-mixer: latest
          sdl2-net: latest
      - name: Inspect local Framework directory
        run: 'find ~/Library/Frameworks'
